### ISSUE TITLE
First UDP call fails every 10min in live tests

### ISSUE THREAD

**Issue by chris-elford-metaswitch** [Metaswitch/clearwater-live-test#117] opened 2016-04-15 08:59 UTC
#### Symptoms
I ran the test case 'Basic Call - Mainline' using UDP and it failed.
I then ran it 20 times and it passed each time.

I waited 10 min and ran it another 20 times. The first call failed. All subsequent ones passed.
I repeated this 3 more times with the same results.

Looking at SAS: My test box sends an INVITE. The call proceeds to the 180 Ringing. At this point, no more messages are sent. SIP timer C (3min) pops on Sprout, and it CANCEL's the call. The test tool should have sent a 200OK to SAS

Seen on a deployment with 1 Bono, 2 Sprout nodes, and 2 Homestead nodes, using Ellis and Homestead prov.

#### Impact
This is causing spurious test failures.

#### Release and environment 
Using clearwater-live-test at commit 7c6b51d85fc239e9ec0765c360589d18006c9c37.

#### Steps to reproduce
Run `rake test[cne.cw-ngv.com] SIGNUP_CODE=<signup_code> TESTS="Basic Call - Mainline" TRANSPORT=UDP`

**Comment by rkd-msw** [comment] 2016-07-26 10:25
I've done some investigation. I'm pretty confident this is caused by large UDP packets.

"Basic Call - Mainline" is the test that usually fails - because this includes full SDP, the 200 OK is 1667 bytes, and from Wireshark trace it looks like that 200 OK gets dropped by EC2 - I see it leaving the test script but never arriving at Bono.

Other tests (Pracks, pager model messages) don't use full SDP in the body, just the string 'Hello world', so their 200 OK responses are <1500 bytes. If I run these tests after a gap of 10 minutes, I don't see a missing message.

Couple of things to try:

* setting the right config flag in the test script so that the 200 OK is retransmitted
* removing the full SDP in favour of a shorter text body so we get smaller messages

**Comment by chris-elford-metaswitch** [comment] 2016-07-27 08:08
Nice one. There is one thing I don't understand here. Why do we hit this cutting the release, but not in our CI setup? Are there some EC2 settings that we should be recommending to users?

**Comment by graemerobertson** [comment] 2016-07-27 08:49
We don't run UDP tests in CI because they're unreliable

**Comment by chris-elford-metaswitch** [comment] 2016-07-27 08:57
That makes sense. I'm guessing that there is nothing we can do to tweak how EC2 handles large packets then.

**Comment by rkd-msw** [comment] 2016-07-27 09:14
And also because the only thing changing is the transport used to Bono - and Bono now changes so infrequently that false positives/EC2 infrastructure stuff/etc. would be more noisy than actual failures.

We do recommend two things to serious users which mitigate this:

* using TCP (as extra IMS headers tend to push packets up above 1300 bytes)
* using a production-quality P-CSCF - if we did topology hiding, there'd be fewer headers on the outbound INVITE and it would be below the packet size limit

**Comment by rkd-msw** [comment] 2016-07-27 09:14
I briefly searched for advice on EC2 and large UDP packets and found nothing.

**Comment by rkd-msw** [comment] 2016-08-10 07:36
Fixed by #126.

**Closed by rkd-msw** 2016-08-10 07:36 UTC
Labels: bug, medium-priority
